#! /usr/bin/env bash
echo "== create Bucket"

# Check if at least one argument is provided
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

REGION=${AWS_DEFAULT_REGION:-eu-central-1}

# 3. Execute the command
aws s3api create-bucket \
    --bucket "$1" \
    --region "$REGION" \
    --create-bucket-configuration LocationConstraint="$REGION" \
    --query Location
