#! /usr/bin/env bash
echo "== delete Bucket"

# Check if at least one argument is provided
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

# 3. Execute the command
aws s3api delete-bucket \
    --bucket "$1"
